#!/usr/bin/env python3
import rospy
import numpy as np

from sensor_msgs.msg import Joy
from std_msgs.msg import Float64MultiArray

vessel_name = "CSEI"


class JoyCtrl(object):
    def __init__(self) -> None:
        self.nu_cmd = np.zeros(3)
        self.angle = 0.0

        # Publishers/Subscribers
        self.nu_cmd_pub = rospy.Publisher(
            f"/{vessel_name}/nu_cmd", Float64MultiArray, queue_size=1)
        self.joy_sub = rospy.Subscriber(
            "/joy", Joy, self.callback, queue_size=1)

        # Messages
        self.nu_cmd_msg = Float64MultiArray()

    def callback(self, data):
        """
            Maps the sixaxis playstation controller inputs
            to the command forces.
        """
        L2 = data.axes[3]
        R2 = data.axes[4]

        lStickY = data.axes[1]
        rStickX = -data.axes[2]

        # calculate command force form joystick input
        self.nu_cmd[0] = lStickY*0.05
        self.nu_cmd[1] = rStickX*0.02
        self.nu_cmd[2] = (L2 - R2)*0.5*0.15

        # Only publish when commands is given from the controller
        if np.linalg.norm(self.nu_cmd) != 0.01:
            self.publish()

        if data.buttons[1] == 1: #X to activate CBF
            self.cbfstate = "CBF ON"
            rospy.logwarn(self.cbfstate)
        elif data.buttons[0] == 1: #Square to deactivate CBF
            self.cbfstate = "CBF OFF"
            rospy.logwarn(self.cbfstate)

    def publish(self):
        """
            Publish command velocities to velocity cmd topic.
        """
        # update message
        self.nu_cmd_msg.data = self.nu_cmd

        # publish message
        self.nu_cmd_pub.publish(self.nu_cmd_msg)


if __name__ == '__main__':
    rospy.init_node("joy_controller")
    rospy.loginfo(f"INITIALIZING {vessel_name}JOYSTICK VELOCITY CONTROLLER NODE")
    r = rospy.Rate(100)

    joyCtrl = JoyCtrl()

    while not rospy.is_shutdown():
        r.sleep()

    rospy.spin()
